### ISSUE TITLE
No time slice for AnalogSignals

### ISSUE THREAD

**Issue by mdenker** [INM-6/python-neo#9]
It would be very useful to slice AnalogSignals by time, just like SpikeTrains.

``` python
l=bl.list_children_by_class("SpikeTrain")[0]
print l.time_slice(0,50000)
l=bl.list_children_by_class("AnalogSignal")[0]
print l.time_slice(0,5000)
```

**Comment by mdenker** [comment]
Code is developed, needs pull request to Neo.

**Comment by alperyeg** [comment]
Where is the code? Can you give a link?

**Comment by mdenker** [comment]
No, I was thinking of Paul's code, but do not know where the latest is, but one version is hidden in here:
https://github.com/mdenker/python-neo/commits/master

However, as we now know, we do not need this anymore, since the AnalogSignalArray (which will become the new AnalogSignal) already has the time slice. So we could actually close this issue I think...

**Comment by mdenker** [comment]
Was ported to neo.
